<?php
/**
 * @var \Pagantis\Pagantis\Block\Product\Simulator $block
 */
if($block->isEnabled4x()===true && $block->getPublicKey4x()!='' && $block->checkValidAmount4x()===true) {
?>
    <style>
        .pg-no-interest{
            color: #00c1d5
        }

        .mainPagantisSimulator {
            font-family: Open Sans,sans-serif!important;
            font-size: 14px!important;
            font-weight: 400;
            text-align: left!important;
            color: #828282!important;
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -ms-user-select: none;
            user-select: none;
            padding: 0 0 10px 0;
            min-width: 250px;
            line-height: 20px;
        }
        .mainPagantisSimulator .mainImageLogo{
            height: 20px;
            display: inline;
            vertical-align: bottom;
        }
    </style>
    <div class="mainPagantisSimulator"><?php echo $block->getSimulatorMessage();?><img class='mainImageLogo' src='https://cdn.digitalorigin.com/assets/master/logos/pg-130x30.svg'/></div>
    <script>
        window.attempts4x = 0;
        function moveToPrice4x() {
            var simnode4x = document.querySelector(findPositionSelector4x());

            var detailnode = document.getElementsByClassName(findDestinationSim4x());
            detailnode = detailnode['0'];

            if (simnode4x != null && detailnode!=null)
            {
                detailnode.parentNode.insertBefore(simnode4x, detailnode);
                window.attempts4x = 10;
            }
        }

        function checkAttempts4x() {
            window.attempts4x = window.attempts4x + 1;
            return (window.attempts4x > 10)
        }

        function findPositionSelector4x() {
            var positionSelector = '<?php echo $block->getPositionSelector();?>';
            if (positionSelector === 'default' || positionSelector === '') {
                positionSelector = '.mainPagantisSimulator';
            }

            return positionSelector;
        }

        function findDestinationSim4x()
        {
            var destinationSim = '<?php echo $block->getDestinationSim();?>';
            if (destinationSim === 'default' || destinationSim == '') {
                destinationSim = 'product-add-form';
            }
            return destinationSim;
        }

        function checkSimulatorContent4x() {
            var pgDiv4x = document.querySelectorAll('product-add-form');
            if (pgDiv4x.length>0) {
                var pgElement4x = pgDiv4x[0];
                if (pgElement4x.innerHTML != '') {
                    return true;
                }
            }

            return false;
        }

        if (checkAttempts4x()===false && checkSimulatorContent4x()===false)
        {
            moveToPrice4x();
        }

    </script>
<?php
}

if($block->isEnabled12x()===true && $block->getProductSimulator()==='1' && $block->getPublicKey()!='') {
    ?>
    <script>// <![CDATA[
        require([
            'jquery',
            'https://cdn.pagantis.com/js/pg-v2/sdk.js'
        ], function ($, pgSdk)
        {
            var moduleEnabled = '<?php echo $block->isEnabled12x();?>';
            var simulatorEnabled = '<?php echo $block->getProductSimulator();?>';
            var publicKey = '<?php echo $block->getPublicKey();?>';
            var locale = '<?php echo $block->getLocale();?>';
            var country = '<?php echo $block->getCountry();?>';
            var allowedCountry = '<?php echo $block->getAllowedCountry($block->getLocale());?>';
            var promotedProduct = '<?php echo $block->getPromoted();?>';
            var simulatorType = '<?php echo $block->getSimulatorType();?>';
            var thousandSeparator = '<?php echo $block->getThousandSeparator();?>';
            var decimalSeparator = '<?php echo $block->getDecimalSeparator();?>';
            var numInstallments = '<?php echo $block->getMinInstallments();?>';
            var validAmount = '<?php echo $block->checkValidAmount();?>';
            var minAmount = '<?php echo $block->getMinAmount();?>';
            var maxAmount = '<?php echo $block->getMaxAmount();?>';
            var totalAmount = '<?php echo $block->getFinalPrice();?>';
            var validAmount4x = '<?php echo $block->checkValidAmount4x();?>';
            var minAmount4x = '<?php echo $block->getMinAmount4x();?>';
            var maxAmount4x = '<?php echo $block->getMaxAmount4x();?>';

            if(moduleEnabled=='1' && simulatorEnabled=='1' && publicKey!='' && allowedCountry=='1' && validAmount=='1'){

                window.sdk = pgSdk;

                function checkSimulatorContent() {
                    var simulatorLoaded = false;
                    var positionSelector = findPositionSelector();
                    var pmtDiv = document.querySelectorAll(positionSelector);
                    if (pmtDiv.length>0 && typeof window.MGSimulatorId!='undefined') {
                        var pmtElement = pmtDiv[0];
                        if (pmtElement.innerHTML != '') {
                            simulatorLoaded = true;
                        }
                    }
                    return simulatorLoaded;
                }

                function findDestinationSim()
                {
                    var destinationSim = '<?php echo $block->getDestinationSim();?>';
                    if (destinationSim === 'default' || destinationSim == '') {
                        destinationSim = 'product-add-form';
                    }
                    return destinationSim;
                }

                function moveToPrice()
                {
                    if (simulatorType === 'sdk.simulator.types.SELECTABLE_TEXT_CUSTOM' ||
                        simulatorType === 'sdk.simulator.types.PRODUCT_PAGE') {
                        var simnode = document.querySelector(findPositionSelector());

                        var detailnode = document.getElementsByClassName(findDestinationSim());
                        detailnode = detailnode['0'];

                        detailnode.parentNode.insertBefore(simnode, detailnode);
                    }
                }

                function checkAttempts() {
                    window.attempts = window.attempts + 1;
                    return (window.attempts > 4)
                }

                function finishInterval() {
                    return clearInterval(window.loadingSimulator);
                }

                function findPriceSelector()
                {
                    var priceSelector = '<?php echo $block->getPriceSelector();?>';
                    if (priceSelector === 'default' || priceSelector === '') {
                        priceSelector = 'div.price-final_price span.price-wrapper span.price';
                    }

                    return priceSelector;
                }

                function findQuantitySelector()
                {
                    var quantitySelector = '<?php echo $block->getQuantitySelector();?>';
                    if (quantitySelector === 'default' || quantitySelector === '') {
                        quantitySelector = 'div.fieldset div.qty div.control input.qty';
                    }

                    return quantitySelector;
                }

                function findPositionSelector() {
                    var positionSelector = '<?php echo $block->getPositionSelector();?>';
                    if (positionSelector === 'default' || positionSelector === '') {
                        positionSelector = '.pagantisSimulator';
                    }

                    return positionSelector;
                }

                function loadSimulator() {
                    if (typeof window.sdk == 'undefined')
                    {
                        return false;
                    }

                    if (checkAttempts() || checkSimulatorContent())
                    {
                        return finishInterval();
                    }
                    else
                    {
                        var priceSelector = findPriceSelector();
                        var quantitySelector = findQuantitySelector();
                        var positionSelector = findPositionSelector();
                        simulator_options = {
                            numInstalments: numInstallments,
                            publicKey: publicKey,
                            type: eval(simulatorType),
                            selector: positionSelector,
                            itemAmountSelector: priceSelector,
                            locale: locale,
                            country: country,
                            amountParserConfig: {
                                thousandSeparator: thousandSeparator,
                                decimalSeparator: decimalSeparator
                            }
                        }
                        
                        var qtyDiv = document.querySelectorAll(quantitySelector);
                        if(qtyDiv.length > 0)
                        { simulator_options.itemQuantitySelector = quantitySelector; }
                        else
                        { simulator_options.itemQuantity = 1; }
                    };

                    if (promotedProduct == 'true') {
                        simulator_options.itemPromotedAmountSelector = priceSelector;
                    }

                    if (typeof window.sdk != 'undefined') {
                        window.MGSimulatorId = window.sdk.simulator.init(simulator_options);
                        if(window.MGSimulatorId != '') {
                            moveToPrice();
                        }
                        return false;
                    }

                    return false;
                }

                window.attempts = 0;
                window.loadingSimulator = setInterval(function () {
                    loadSimulator();
                }, 2000);
            }
        });
        // ]]>
    </script>
    <style>
        .pg-no-interest{
            color: #00c1d5
        }
        .promoted{
            width: 75%;
            margin: auto;
        }
    </style>
    <?php
        if ($block->getPromoted() == 'true') {
            echo $block->getPromotedMessage();
        }
    ?>
    <style>
        select.pg-sim-custom-selector-control {
            width: 55px;
        }
    </style>
    <div class="pagantisSimulator" style="display: flex"></div>
    <p></p>
    <?php
}
?>
