<?php
/**
 * @var \Pagantis\Pagantis\Block\Product\Simulator $block
 */
if($block->isEnabled()==='1' && $block->getProductSimulator()==='1' && $block->getPublicKey()) {
    ?>
    <script>// <![CDATA[
        require([
            'jquery',
            'https://cdn.pagamastarde.com/js/pmt-v2/sdk.js',
            'https://cdn.pagantis.com/js/pg-v2/sdk.js'
        ], function ($, pmtSdk, pgSdk) {
            var moduleEnabled = '<? echo $block->isEnabled();?>';
            var simulatorEnabled = '<? echo $block->getProductSimulator();?>';
            var publicKey = '<? echo $block->getPublicKey();?>';
            var locale = '<? echo $block->getLocale();?>';
            var country = '<? echo $block->getCountry();?>';
            var allowedCountry = '<? echo $block->getAllowedCountry($block->getLocale());?>';
            var promotedProduct = '<? echo $block->getPromoted();?>';
            var simulatorType = '<? echo $block->getSimulatorType();?>';
            var thousandSeparator = '<? echo $block->getThousandSeparator();?>';
            var decimalSeparator = '<? echo $block->getDecimalSeparator();?>';
            var numInstallments = '<? echo $block->getMinInstallments();?>';

            if(moduleEnabled=='1' && simulatorEnabled=='1' && publicKey!='' && allowedCountry=='1') {

                if (locale == 'es' || locale=='')
                {
                    window.sdk = pmtSdk;
                } else {
                    window.sdk = pgSdk;
                }

                function checkSimulatorContent() {
                    var simulatorLoaded = false;
                    var positionSelector = findPositionSelector();
                    var pmtDiv = document.querySelectorAll(positionSelector);
                    if (pmtDiv.length>0 && typeof window.MGSimulatorId!='undefined') {
                        var pmtElement = pmtDiv[0];
                        if (pmtElement.innerHTML != '') {
                            simulatorLoaded = true;
                        }
                    }
                    return simulatorLoaded;
                }

                function checkAttempts() {
                    window.attempts = window.attempts + 1;
                    return (window.attempts > 4)
                }

                function finishInterval() {
                    clearInterval(window.loadingSimulator);
                    return true;
                }

                function findPriceSelector()
                {
                    var priceSelector = '<? echo $block->getPriceSelector();?>';
                    if (priceSelector === 'default' || priceSelector === '') {
                        priceSelector = 'div.price-final_price span.price-wrapper span.price';
                    }

                    return priceSelector;
                }

                function findQuantitySelector()
                {
                    var quantitySelector = '<? echo $block->getQuantitySelector();?>';
                    if (quantitySelector === 'default' || quantitySelector === '') {
                        quantitySelector = 'div.fieldset div.qty div.control input.qty';
                    }

                    return quantitySelector;
                }

                function findPositionSelector() {
                    var positionSelector = '<? echo $block->getPositionSelector();?>';
                    if (positionSelector === 'default' || positionSelector === '') {
                        positionSelector = '.pagantisSimulator';
                    }

                    return positionSelector;
                }

                function loadSimulator() {
                    if(typeof window.sdk == 'undefined')
                    {
                        return false;
                    }

                    if (checkAttempts() || checkSimulatorContent())
                    {
                        return finishInterval();
                    }

                    var priceSelector = findPriceSelector();
                    var quantitySelector = findQuantitySelector();
                    var positionSelector = findPositionSelector();
                    simulator_options = {
                        numInstalments : numInstallments,
                        publicKey: publicKey,
                        type: simulatorType,
                        selector: positionSelector,
                        itemQuantitySelector: quantitySelector,
                        itemAmountSelector: priceSelector,
                        locale : locale,
                        country : country,
                        amountParserConfig :  {
                            thousandSeparator: thousandSeparator,
                            decimalSeparator: decimalSeparator
                        }
                    };

                    if (promotedProduct == 'true') {
                        simulator_options.itemPromotedAmountSelector = priceSelector;
                    }

                    if (typeof window.sdk != 'undefined') {
                        window.MGSimulatorId = window.sdk.simulator.init(simulator_options);
                        return false;
                    }

                    return false;
                }

                window.attempts = 0;
                window.loadingSimulator = setInterval(function () {
                    loadSimulator();
                }, 2000);
            }
        });
        // ]]>
    </script>
    <style>
        .pmt-no-interest{
            color: #00c1d5
        }
        .promoted{
            width: 75%;
            margin: auto;
        }
    </style>
    <?php
        if ($block->getPromoted() == 'true') {
            echo $block->getPromotedMessage();
        }
    ?>
    <div class="pagantisSimulator"></div>
    <p></p>
    <?php
}
?>
