<?php
/**
 * @var \Pagantis\Pagantis\Block\Product\Simulator $block
 */
if($block->isEnabled()==='1') {
?>
    <script
            src="https://js.afterpay.com/afterpay-1.x.js"
            data-min="<?php echo $block->getMinAmount();?>"
            data-max="<?php echo $block->getMaxAmount();?>"
            async
            defer
    ></script>
    <div class="mainSimulator">
        <!-- Begin Afterpay Placement -->
        <!--
                data-locale="<?php echo $block->getLocale();?>"
                data-currency="<?php echo $block->getCurrency();?>"
        -->
        <afterpay-placement
                data-amount="<?php echo $block->getAmount();?>"
        ></afterpay-placement>
        <!-- End Afterpay Placement -->
    </div>
<?php
}
?>
