<?php
/**
 * @var \DigitalOrigin\Pmt\Block\Payment\Iframe $block
 */

//if ($block->url && $block->checkoutUrl) {
?>
<script type="text/javascript">
    require.config({
        paths: { "pmtSdk": "https://cdn.pagamastarde.com/pmt-js-client-sdk/3/js/client-sdk.min"},
        waitSeconds: 0
    });

    require( ["pmtSdk", "jquery" ],
        function (pmtClient, $) {
            if (typeof pmtClient !== 'undefined') {
                $(document).ready( function(){
                    pmtClient.modal.open(
                        "<?=$block->getOrderUrl(); ?>",
                        {
                            closeOnBackDropClick: false,
                            closeOnEscPress: false,
                            backDropDark: false,
                            largeSize: true,
                            closeConfirmationMessage: "{l s='Sure you want to leave?' mod='paylater'}"
                        }
                    );
                });
                pmtClient.modal.onClose(function() {
                    window.location.href = "<?=$block->getCheckoutUrl(); ?>";
                });
            }
        }
    );
</script>
<?php
//}
?>

