<script type="text/javascript">
    require( [
        "https://cdn.pagantis.com/js/pg-v2/sdk.js", "jquery" ],
        function (pgSDK, $) {
            if (typeof pgSDK !== 'undefined') {
                $(document).ready( function(){
                    pgSDK.modal.open(
                        "<?=$block->getOrderUrl(); ?>",
                        {
                            closeOnBackDropClick: false,
                            closeOnEscPress: false,
                            backDropDark: false,
                            largeSize: true,
                            closeConfirmationMessage: "{l s='Sure you want to leave?' mod='pagantis'}"
                        }
                    );
                });
                pgSDK.modal.onClose(function() {
                    window.location.href = "<?=$block->getCheckoutUrl(); ?>";
                });
            }
        }
    );
</script>
